services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - CORS_ORIGINS=http://frontend:3000
    volumes:
      - ./data:/app/data
      - ./seed:/app/seed
    expose:
      - "8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://nginx:8010/api
    expose:
      - "3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    expose:
      - "8010"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
