services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: edm-backend
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - CORS_ORIGINS=http://localhost:8010,http://frontend:3000
    volumes:
      - ./data:/app/data
      - ./seed:/app/seed
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: edm-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8010/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: edm-nginx
    ports:
      - "8010:8010"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
