version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: edm-backend-dev
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - CORS_ORIGINS=http://localhost:8010,http://localhost:3000
    volumes:
      - ./data:/app/data
      - ./seed:/app/seed
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: edm-frontend-dev
    environment:
      - REACT_APP_API_URL=http://localhost:8010/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: edm-nginx-dev
    ports:
      - "8010:8010"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
